pipeline:
  identifier: Build_NidaAP_gitopscalculator_1722500963269
  name: Build gitopscalculator
  orgIdentifier: default
  projectIdentifier: harnessCICD_windows_connector
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1719218752184
        repoName: NidaAP/gitopscalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
